### ISSUE TITLE
Support for multiple and arbitrary gateways

### ISSUE THREAD

**Issue by maxgio92** [angelnu/gateway-admision-controller#102]
# Details

**Describe the solution you'd like:**

Add support for having multiple [pod-gateway](https://github.com/angelnu/pod-gateway/)s inside a single cluster and allow the end-user, to select for each client application which pod-gateway set as the default gateway for the client application's pods.

**Anything else you would like to add:**

###### At Pod level

In the simpler form, and allowing the application owner - who, in a DevOps way, would be responsible for configuring their own application's deployment - this could be implemented through annotations at pod-level.

The mutating admission wehbook would inject the `$gateway` environment variable to client pods' init and sidecar containers.

You can see a draft implementation [here](https://github.com/maxgio92/gateway-admision-controller/tree/feat/multi-gateway).

###### At Namespace level

Assuming the following:
- the injection should happen transparently (e.g. as part of a policy enforcement) and managed by an administrator which would choose through which gateway should applications' traffic go through
- Namespaces are objects managed by administrators

an annotation that would hint which gateway to use as Kubernetes Service name, could be applied at Namespace-level.

The mutating admission wehbook would inject the `$gateway` environment variable to client pods' init and sidecar containers.

###### Other

Obviously the way the feature could be achieved is not limited to the above proposed approaches.

**Additional Information:**

The VXLAN CIDR blocks, for each VXLAN static network (one per gateway) might be able to overlap and this shoudn't be a problem.

This is just a screenshot that shows client pods on the left panes, and gateway pods on the right panes.
The top panes represent a tunnel separated from the bottom one.

The client of which the shells on the left, knows from the `$gateway` environment variable, from the headless Kubernetes `Service`, the pod-gateway pod-network's IP (from which the init container build the Linux bridge FDB rule):

```shell
$ kubectl get pods -n client -o=jsonpath='{.items[*].spec.initContainers[*].env[0]}' | jq                                                                                                           
{
  "name": "gateway",
  "value": "pod-gateway-a.gateway-system.svc.cluster.local"
}
{
  "name": "gateway",
  "value": "pod-gateway-b.gateway-system.svc.cluster.local"
}
```

`pod-gateway-a` and `pod-gateway-b` are the Kubernetes `Service` object names that have the `pod-gateway-a` and `pod-gateway-b` deployment with one replica, residing in the `gateway-system` `Namespace`:

```shell
$kubectl get svc -n gateway-system -o wide                                                                                                                                                         
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE   SELECTOR
pod-gateway-a         ClusterIP   None            <none>        4789/UDP   20h   app.kubernetes.io/instance=pod-gateway-a,app.kubernetes.io/name=pod-gateway
pod-gateway-b         ClusterIP   None            <none>        4789/UDP   20h   app.kubernetes.io/instance=pod-gateway-b,app.kubernetes.io/name=pod-gateway
pod-gateway-webhook   ClusterIP   10.96.119.198   <none>        8080/TCP   21h   app.kubernetes.io/instance=pod-gateway,app.kubernetes.io/name=pod-gateway-webhook

$ kubectl get ep -n gateway-system                                                                                                                                                                  
NAME                  ENDPOINTS             AGE
pod-gateway-a         192.168.228.11:4789   20h
pod-gateway-b         192.168.228.14:4789   20h
pod-gateway-webhook   192.168.228.9:8080    21h

$ kubectl get deploy -n gateway-system -o wide                                                                                                                                                      
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS    IMAGES                                                                    SELECTOR
pod-gateway-a         1/1     1            1           20h   pod-gateway   ghcr.io/k8s-at-home/pod-gateway:v1.6.1                                    app.kubernetes.io/instance=pod-gateway-a,app.kubernetes.io/name=pod-gateway
pod-gateway-b         1/1     1            1           20h   pod-gateway   ghcr.io/k8s-at-home/pod-gateway:v1.6.1                                    app.kubernetes.io/instance=pod-gateway-b,app.kubernetes.io/name=pod-gateway
pod-gateway-webhook   1/1     1            1           21h   webhook       quay.io/maxgio92/gateway-admission-controller:v3.7.1-alpha-multigateway   app.kubernetes.io/instance=pod-gateway,app.kubernetes.io/name=pod-gateway-webhook
```

![image](https://user-images.githubusercontent.com/7593929/213675250-c05532e4-1cc9-495b-a257-4da321f581c9.png)

As you can see the gateway VXLAN IPs overlap (i.e. 172.16.0.1) but the Linux FDB together with VXLAN capabilities of the device (drivers) manage for dedicated MAC addresses.

![image](https://user-images.githubusercontent.com/7593929/213693943-9e1a6926-5459-4825-b565-2122bb290145.png)

#### More: multiple clients per each gateway and IP management

In the example scenario of the screenshot above, client VXLAN IP addresses have been statically assigned.
DHCP, of which [server](https://github.com/angelnu/pod-gateway/blob/main/bin/gateway_sidecar.sh#L22) and [client](https://github.com/angelnu/pod-gateway/blob/main/bin/client_init.sh#L61) setup already provided by the pod-gateway feature set, can manage them.

**Comment by kalik1** [comment]
Great Job! Thank you!

**Comment by angelnu** [comment]
Thanks for the proposal @maxgio92 - very well formulated!

It is currently possible to deploy multiple gateways but each of the would be bound to a particular namespace or using different labels/annotations (see [helm chart](https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gateway/values.yaml#L139-L145)).

I would like to keep compatibility with todays annotations. This might be achieved by adding ´setGatewayAnnotationValue´ in addition to the existing `setGatewayAnnotation`. When `setGatewayAnnotationValue` is set, then the annotation value would also need to match beyond just being true. This would allow to pod-gateways to use the same `setGatewayAnnotation` string but different `setGatewayAnnotationValue` values.  For simatry we should also do the same extension for labels.

**Comment by maxgio92** [comment]
Thank you @angelnu (I think you put your answer inside my comment :/).

I think we can go this way: I can open a PR with the simple implementation you proposed which has the minor impact, as of now.
From the end-user perspective additionals admission controller's flags will be available:
- `--setGatewayLabelValue`
- `--setGatewayAnnotationValue`

in order to, not only require that the label/annotation of which the key is specified by the flag `--setGatewayLabel`/`--setGatewayAnnotation`, or the default `'setGateway'`, has a value of `'true'`, but that it matches the value specified by the flag `--setGatewayLabelValue`/`--setGatewayAnnotationValue`.

For example, in order to have multiple gateways:

```
// run gateway "foo" deployment
gateway-admission-controller [...] --setGatewayAnnotation=inject-gateway --setGatewayAnnotationValue=foo
kubectl run [...] --annotations="inject-gateway=foo"
```

```
// run gateway "bar" deployment
gateway-admission-controller [...] --setGatewayAnnotation=inject-gateway --setGatewayAnnotationValue=bar
kubectl run [...] --annotations="inject-gateway=bar"
```

WDYT?

**Comment by angelnu** [comment]
Sorry for commenting in directly in your post and not in a copy x-/

I agree with your proposal. So please go ahead. The helm chart will also need an update to expose the new parameter.

**Comment by maxgio92** [comment]
No problem at all @angelnu. Thanks. PTAL at #103 :-)

**Comment by angelnu** [comment]
Thanks for the PR! Would you be able to do a PR to Helm chart as well?

**Comment by maxgio92** [comment]
Hi @angelnu, [here](https://github.com/angelnu/helm-charts/pull/49) it is :-)
